db:
  url: jdbc:mysql://localhost:3306/tower?useUnicode=true&characterEncoding=utf-8
  userName: root
  passowrd: cxy910527
  driver: com.mysql.jdbc.Driver

custom:
  tmpLocation: /opt/gray/fileupload

spring:
  session:
    store-type: HASH_MAP
  cache:
    type: None
