db:
  url: jdbc:mysql://localhost:3306/tower?useUnicode=true&characterEncoding=utf-8
  userName: root
  passowrd: cxy910527
  driver: com.mysql.jdbc.Driver

custom:
  tmpLocation: D:/image

spring:
  session:
    store-type: HASH_MAP
  cache:
    type: None
  redis:
    host: 127.0.0.1
    password: cxy910527
    port: 6379
    pool:
      max-active: 8