db:
  url: jdbc:mysql://localhost:3306/xj?useUnicode=true&characterEncoding=utf-8
  userName: root
  passowrd: 512382762
  driver: com.mysql.jdbc.Driver

custom:
  tmpLocation: D:/image

spring:
  session:
    store-type: HASH_MAP
  cache:
    type: None
